version: '3'

services:
  mongodb:
    image: mongo:latest
    environment:
        MONGO_INITDB_DATABASE: espndb
    ports:
      - "27017:27017"
    restart: always

  crawler:
    build: ./crawler
    depends_on:
      - mongodb

  api:
    build: ./espn-api
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    restart: always
